---
title: "pooled estimates"
output: pdf_document
date: "2024"
---

```{r setup, results = "hide", messages = F, echo = F, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xtable)
library(JMbayes2)
```

\newpage
# Compare MI estimates

```{r function combine MI bayesian}
# help function
combine_obs_bayes <- function(fit_file) {
  load(fit_file)
  posterior <- cbind(
    do.call(rbind, fit_jm[["mcmc"]][["betas1"]][1:3]),
    do.call(rbind, fit_jm[["mcmc"]][["gammas"]][1:3]),
    do.call(rbind, fit_jm[["mcmc"]][["alphas"]][1:3])
  )
  
  print(max(c(fit_jm[["statistics"]][["Rhat"]][["betas1"]][,1], 
              fit_jm[["statistics"]][["Rhat"]][["gammas"]][,1],
              fit_jm[["statistics"]][["Rhat"]][["alphas"]][,1], 
              fit_jm[["statistics"]][["Rhat"]][["sigmas"]][,1])))
  a <-  unlist(fit_jm[["acc_rates"]])
  print(min((a[a!=0])))
  print(max((a[a!=0])))
 rm(fit_jm)
  list(
    delta = "NA",
    est = apply(posterior, 2, mean),
    est_se = apply(posterior, 2, sd),
    q2.5 = apply(posterior, 2, quantile, probs = 0.025),
    q97.5 = apply(posterior, 2, quantile, probs = 0.975)
  )
}
combine_mi_est_bayes <- function(directory, vector_of_file_names, delta) {
  print(paste0("Combining MI estimates from files: ", vector_of_file_names, collaspe = ""))

  posterior <- matrix(nrow = 0, ncol = 13)
  max_r_hat <- numeric(length(vector_of_file_names))
  acc_min <- numeric(length(vector_of_file_names))
  acc_max <- numeric(length(vector_of_file_names))
  for (i in 1:length(vector_of_file_names)) {
    # read the fit
    load(paste0(directory, vector_of_file_names[i], sep = ""))
    # combine posterior draws from chains in  one imputation
    posterior_i <- cbind(
      do.call(rbind, fit_jm[["mcmc"]][["betas1"]][1:3]),
      do.call(rbind, fit_jm[["mcmc"]][["gammas"]][1:3]),
      do.call(rbind, fit_jm[["mcmc"]][["alphas"]][1:3])
    )
    max_r_hat[i] <- max(c(fit_jm[["statistics"]][["Rhat"]][["betas1"]][,1], 
                          fit_jm[["statistics"]][["Rhat"]][["gammas"]][,1],
                          fit_jm[["statistics"]][["Rhat"]][["alphas"]][,1],
                          fit_jm[["statistics"]][["Rhat"]][["sigmas"]][,1]))
    
    a <-  unlist(fit_jm[["acc_rates"]])
    acc_min[i] <- min((a[a!=0]))
    acc_max[i] <- max((a[a!=0]))
    rm(fit_jm)
   
    # add  rows of posterior draws for imputation i to a combined posterior
    posterior <- rbind(posterior, posterior_i)
  }
  print(max_r_hat)
  print(acc_min)
  print(acc_max)
  list(
    delta = delta,
    est = apply(posterior, 2, mean),
    est_se = apply(posterior, 2, sd),
    q2.5 = apply(posterior, 2, quantile, probs = 0.025),
    q97.5 = apply(posterior, 2, quantile, probs = 0.975)
  )
}

```



```{r pool parameters}
est_obs <- combine_obs_bayes(fit_file = "../results/fit_jm_observed.Rdata")

names_all_files <- list.files("../results/")
est_delta0 <- combine_mi_est_bayes(
  directory = "../results/",
  vector_of_file_names = names_all_files[grep("fit_jm_delta_0", names_all_files)],
  delta = 0
)
est_delta_1_if_dropout_after_60 <- combine_mi_est_bayes(
  directory = "../results/",
  vector_of_file_names = names_all_files[grep("fit_jm_delta__1", names_all_files)],
  delta = "-1 only if dropout after 60"
)
est_delta_delta_depends_on_age <- combine_mi_est_bayes(
  directory = "../results/",
  vector_of_file_names = names_all_files[grep("fit_jm_delta_changing", names_all_files)],
  delta = "delta depends on age"
)

est_delta_1_if_dropout_after_65 <- combine_mi_est_bayes(
  directory = "../results/cutoff_65/",
  vector_of_file_names = list.files("../results/cutoff_65/"),
  delta = "-1 only if dropout after 65")

est_delta_1_if_dropout_after_55 <- combine_mi_est_bayes(
  directory = "../results/cutoff_55/",
  vector_of_file_names = list.files("../results/cutoff_55/"),
  delta = "-1 only if dropout after 55")
```

```{r table est and CIs}
est_to_show <- function(est) {
  # paste0(sprintf("%.1E", est$est), " (", sprintf("%.1E", est$q2.5), ", ", sprintf("%.1E", est$q97.5), ")")
  paste0(round(est$est,2), " (", round(est$q2.5, 2), ", ", round(est$q97.5 ,2), ")")
}
results <- data.frame(
  est_to_show(est_obs),
  est_to_show(est_delta0),
  est_to_show(est_delta_delta_depends_on_age),
  est_to_show(est_delta_1_if_dropout_after_60),
  est_to_show(est_delta_1_if_dropout_after_55),
  est_to_show(est_delta_1_if_dropout_after_65)
)
names(results) <- gsub("\\.", "", gsub("est_to_show.est_delta", "", names(results)))
parameter_names <- gsub("age - mean_age", "t-bar{t}", names(est_delta0[["est"]])) # substitute age_sc20 - mean_age_sc20 by t in names of the parameters
results <- cbind(parameter_names, results)

print(
  xtable(results,
    digits = 0
  ),
  include.rownames = FALSE
)
```
```{r}
results <- data.frame(
   est_to_show(est_delta_1_if_dropout_after_55),
  est_to_show(est_delta_1_if_dropout_after_60),
  est_to_show(est_delta_1_if_dropout_after_65)
)
names(results) <- gsub("\\.", "", gsub("est_to_show.est_delta", "", names(results)))
parameter_names <- gsub("age - mean_age", "t-bar{t}", names(est_delta0[["est"]])) # substitute age_sc20 - mean_age_sc20 by t in names of the parameters
results <- cbind(parameter_names, results)

print(
  xtable(results,
    digits = 0
  ),
  include.rownames = FALSE
)
```

```{r}
results
```

```{r table standard errors}
standard_errors <- data.frame(
  est_obs$est_se,
  est_delta0$est_se,
  est_delta_delta_depends_on_age$est_se,
  est_delta_1_if_dropout_after_60$est_se
)
names(standard_errors) <- gsub("est_delta", "", gsub("\\.est_se", "", names(standard_errors)))
parameter_names <- gsub("age - mean_ag", "t- bar{t}", names(est_delta0[["est"]])) # substitute age_sc20 - mean_age_sc20 by t in names of the parameters
standard_errors <- cbind(parameter_names, standard_errors)

print(
  xtable(standard_errors,
    digits = 2
  ),
  include.rownames = FALSE
)
```

