---
title: "report"
output: pdf_document
date: "2023-04-28"
---

```{r setup, results = "hide", messages = F, echo = F, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xtable)
library(JMbayes2)
```

\newpage
# Compare MI estimates

```{r function combine MI bayesian}
# help function
combine_mi_est_bayes <- function(vector_of_file_names, delta) {
  print(paste0("Combining MI estimates from files: ", vector_of_file_names, collaspe = ""))

  posterior <- matrix(nrow = 0, ncol = 13)
  for (i in 1:length(vector_of_file_names)) {
    # read the fit
    load(paste0("../results/", vector_of_file_names[i], sep = ""))
    # combine posterior draws from chains in  one imputation
    posterior_i <- cbind(
      do.call(rbind, fit_jm[["mcmc"]][["betas1"]][1:3]),
      do.call(rbind, fit_jm[["mcmc"]][["gammas"]][1:3]),
      do.call(rbind, fit_jm[["mcmc"]][["alphas"]][1:3])
    )
    rm(fit_jm)
    # add  rows of posterior draws for imputation i to a combined posterior
    posterior <- rbind(posterior, posterior_i)
  }

  list(
    delta = delta,
    est = apply(posterior, 2, mean),
    est_se = apply(posterior, 2, sd),
    q2.5 = apply(posterior, 2, quantile, probs = 0.025),
    q97.5 = apply(posterior, 2, quantile, probs = 0.975)
  )
}
combine_obs_bayes <- function(fit_file) {
  load(fit_file)
  posterior <- cbind(
    do.call(rbind, fit_jm[["mcmc"]][["betas1"]][1:3]),
    do.call(rbind, fit_jm[["mcmc"]][["gammas"]][1:3]),
    do.call(rbind, fit_jm[["mcmc"]][["alphas"]][1:3])
  )
  rm(fit_jm)

  list(
    delta = "NA",
    est = apply(posterior, 2, mean),
    est_se = apply(posterior, 2, sd),
    q2.5 = apply(posterior, 2, quantile, probs = 0.025),
    q97.5 = apply(posterior, 2, quantile, probs = 0.975)
  )
}
```



```{r pool parameters}
names_all_files <- list.files("../results")
est_delta0 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta0_", names_all_files)],
  delta = 0
)
est_delta05 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta_0.5_", names_all_files)],
  delta = -0.5
)
est_delta1 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta_1_", names_all_files)],
  delta = -1
)
est_delta2 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta_2_", names_all_files)],
  delta = -2
)
est_delta5 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta_5_", names_all_files)],
  delta = -5
)
est_delta10 <- combine_mi_est_bayes(
  vector_of_file_names = names_all_files[grep("fit_jm_delta_10_", names_all_files)],
  delta = -10
)
est_obs <- combine_obs_bayes("../results/fit_jm_observed.Rdata")
```

```{r table est and CIs}
est_to_show <- function(est) {
  paste0(round(est$est, 2), " (", round(est$q2.5, 2), ", ", round(est$q97.5, 2), ")")
}
results <- data.frame(
  est_to_show(est_obs),
  est_to_show(est_delta0),
  est_to_show(est_delta05),
  est_to_show(est_delta1),
  est_to_show(est_delta2),
  est_to_show(est_delta5),
  est_to_show(est_delta10)
)
names(results) <- gsub("\\.", "", gsub("est_to_show.est_delta", "", names(results)))
parameter_names <- gsub("age_sc20 - mean_age_sc20", "t", names(est_delta0[["est"]])) # substitute age_sc20 - mean_age_sc20 by t in names of the parameters
results <- cbind(parameter_names, results)

print(
  xtable(results,
    digits = 0
  ),
  include.rownames = FALSE
)
```

```{r table standard errors}
standard_errors <- data.frame(
  est_obs$est_se,
  est_delta0$est_se,
  est_delta05$est_se,
  est_delta1$est_se,
  est_delta2$est_se,
  est_delta5$est_se,
  est_delta10$est_se
)
names(standard_errors) <- gsub("est_delta", "", gsub("\\.est_se", "", names(standard_errors)))
parameter_names <- gsub("age_sc20 - mean_age_sc20", "t", names(est_delta0[["est"]])) # substitute age_sc20 - mean_age_sc20 by t in names of the parameters
standard_errors <- cbind(parameter_names, standard_errors)

print(
  xtable(standard_errors,
    digits = 2
  ),
  include.rownames = FALSE
)
```

```{r figure estimated trends}
age <- seq(35, 100, length.out = 100)
age_sc20 <- (age - 20) / 100
load("..//dat.Rdata")
mean_age_sc20 <- unique(dat_long$mean_age_sc20)
EM_cc_mean <- unique(dat_long$EM_cc_mean)
EM_cc_sd <- unique(dat_long$EM_cc_sd)
rm(dat_long, dat_surv)
data <- as.matrix(data.frame(1, age_sc20 - mean_age_sc20, (age_sc20 - mean_age_sc20)^2, (age_sc20 - mean_age_sc20)^3))



predict_trajectory <- function(method, estimate) {
  data.frame(
    method = method,
    age = age,
    predicted = data %*% matrix(estimate[["est"]][1:4] * EM_cc_sd + EM_cc_mean, ncol = 1)
  )
}

predicted_all_trajectories <- rbind(
  predict_trajectory(method = "obs", estimate = est_obs),
  predict_trajectory(method = "0", estimate = est_delta0),
  predict_trajectory(method = "-0.5", estimate = est_delta05),
  predict_trajectory(method = "-1", estimate = est_delta1),
  predict_trajectory(method = "-2", estimate = est_delta2),
  predict_trajectory(method = "-5", estimate = est_delta5),
  predict_trajectory(method = "-10", estimate = est_delta10)
) %>%
  mutate(
    method = factor(method, levels = c("obs" ,"0", "-0.5", "-1", "-2", "-5", "-10"),
                    labels = c("obs", "Delta = 0", "Delta = -0.5", 
                    "Delta = -1", "Delta = -2", "Delta = -5", "Delta = -10"))
  )
  

pdf(
  file = "Figure_estmated_mean_time_trend.pdf",
  width = 6, # The width of the plot in inches
  height = 3
)


predicted_all_trajectories%>%
  ggplot() +
  geom_line(aes(x = age, y = predicted, linetype = method))+
  theme_classic() +
  xlab("Age") +
  ylab("Memory")
  
dev.off()


```


```{r figure estimated link}
# age <- seq(35, 100, length.out = 100)
# age_sc20 <- (age - 20) / 100
# load("..//dat.Rdata")
# mean_age_sc20 <- unique(dat_long$mean_age_sc20)
# EM_cc_mean <- unique(dat_long$EM_cc_mean)
# EM_cc_sd <- unique(dat_long$EM_cc_sd)
# rm(dat_long, dat_surv)
# data <- as.matrix(data.frame(1, age_sc20 - mean_age_sc20, (age_sc20 - mean_age_sc20)^2, (age_sc20 - mean_age_sc20)^3))
# data_slope <- as.matrix(data.frame(0, 1, (age_sc20 - mean_age_sc20)*2, (age_sc20 - mean_age_sc20)^2*3))
# 
# 
# 
# predict_trajectory <- function(method, estimate) {
#   data.frame(
#     method = method,
#     age = age,
#     predicted = data %*% matrix(estimate[["est"]][1:4] * EM_cc_sd + EM_cc_mean, ncol = 1),
#     predicted_slope = data_slope %*% matrix(estimate[["est"]][1:4] * EM_cc_sd + EM_cc_mean, ncol = 1)
#   )%>%
#     mutate(predicted_link = predicted*estimate[["est"]][[12]] + predicted_slope*estimate[["est"]][[13]] )
# }
# 
# predicted_all_trajectories <- rbind(
#   predict_trajectory(method = "obs", estimate = est_obs),
#   predict_trajectory(method = "0", estimate = est_delta0),
#   predict_trajectory(method = "-0.5", estimate = est_delta05),
#   predict_trajectory(method = "-1", estimate = est_delta1),
#   predict_trajectory(method = "-2", estimate = est_delta2),
#   predict_trajectory(method = "-5", estimate = est_delta5),
#   predict_trajectory(method = "-10", estimate = est_delta10)
# ) %>%
#   mutate(
#     method = factor(method, levels = c("obs" ,"0", "-0.5", "-1", "-2", "-5", "-10"),
#                     labels = c("obs", "Delta = 0", "Delta = -0.5", 
#                     "Delta = -1", "Delta = -2", "Delta = -5", "Delta = -10"))
#   )
#   
# 
# 
# 
# predicted_all_trajectories%>%
#   ggplot() +
#   geom_line(aes(x = age, y = predicted_link, linetype = method))+
#   theme_classic() +
#   xlab("Age") +
#   ylab("Link")
#   
# 


```
